### ISSUE TITLE
New issues with connecting SoundCloud account

### ISSUE THREAD

**Issue by SpaceCowboy3000** [superturboryan/WatchCloud-Privacy-Policy#2]
After successfully using WatchCloud for a long time, I have been asked to connect it tot the account again (this happened before a number of times with no issues).

However when I try to connect to the app on my phone, I do get an error message.
![IMG_0031](https://github.com/user-attachments/assets/4c77eac6-5031-4164-9ce1-ac18be515f65)

All other attempts to connect via AppleId or gmail also failed.

The issue has been recurring for the past few days.

**Comment by superturboryan** [comment]
Hey mate, I'm currently invesitgating this issue as it seems to be affecting all users. 

Thanks for your patience while I find a solution 🤞

I have opened a separate issue on the SoundCloud API issue tracker where I'm awaiting an answer on what I think may be causing this: https://github.com/soundcloud/api/issues/312

cc @MariaVW @JordanPett

**Comment by superturboryan** [comment]
This seems to be resolved now by a change on SoundCloud's side 🧡 see mentioned issue on the public API issue tracker. 

I'll leave this issue open for a day or two and continue monitoring metrics before closing 🤞

**Comment by SpaceCowboy3000** [comment]
The error no longer pops up and login is successful. Thank you very much! WatchCloud is a real saver - cannot imagine what I would have done without it.

**Comment by superturboryan** [comment]
Thanks for the kind words mate! I was panicking because I’m going on holiday tomorrow and I don’t have time to work on this, luckily it was fixed on SoundCloud’s side! Cheers

**Comment by Psyclop** [comment]
I am a new customer and still experiencing this issue. Any ideas what is wrong?
